# Generated by Django 4.0.4 on 2022-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='profile',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
