# Generated by Django 4.0.4 on 2022-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_user_profile_user_alter_profile_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ProfilePicture',
        ),
        migrations.AddField(
            model_name='profile',
            name='ProfilePhoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
