# Generated by Django 4.0.4 on 2022-08-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_user_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePhoto',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
