# Generated by Django 4.0.4 on 2022-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePhoto',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
